// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaX2MBI2Uk8Qnil_AtqmxuHErBcK0qQQ',
    appId: '1:817332149423:web:ceee03f6beab6cc262c85a',
    messagingSenderId: '817332149423',
    projectId: 'trade-wign-bd',
    authDomain: 'trade-wign-bd.firebaseapp.com',
    storageBucket: 'trade-wign-bd.firebasestorage.app',
    measurementId: 'G-PY3ZQBHTC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0u3o1M0L-dazisvK66pR-Gfk15-Az1vw',
    appId: '1:817332149423:android:34ce03f877f8faf962c85a',
    messagingSenderId: '817332149423',
    projectId: 'trade-wign-bd',
    storageBucket: 'trade-wign-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA746XR1paRsnJ0XRIZeO76CBtqFjnuHms',
    appId: '1:817332149423:ios:9224d1905dd1bbee62c85a',
    messagingSenderId: '817332149423',
    projectId: 'trade-wign-bd',
    storageBucket: 'trade-wign-bd.firebasestorage.app',
    iosBundleId: 'com.ayattech.tradeWignBd',
  );
}
